[colors.terminal.action_start]

fg = 0x7BADE2
emphasis = [ "bold" ]


[colors.terminal.resource]

fg = 0xC384D7


[colors.terminal.success]

fg = 0x26CEAA
emphasis = [ "bold" ]


[colors.terminal.partial_success]

fg = 0x9AE8C1


[colors.terminal.notification]

fg = 0xFF9856


[colors.terminal.exception]

fg = 0xA50162


[colors.terminal.warning]

fg = 0xEF7427


[colors.terminal.callisto]

fg = 0xA359BB
