[variables]  
# Section for user-defined variables
# you can use these anywhere inside strings in this 
# config file by wrapping the name of the variable
# in curly braces, i.e. if you have a 
#     var = "hello"
# variable, you can set the project ROM name to 
# "hello.smc" by doing
#     project_rom = "{var}.smc" 
# later on 

project_name = "my_hack"

project_root = "../.."
